name: Run Script

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      ecr:
        type: string
        required: true
        default: "test-chart-name-long"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Get chart name
        shell: bash
        run: |
          if [[ ${{ inputs.ecr }} == *"cwp"* ]];
          then
              echo "String contains substring."
          else
              echo "String does not contain substring."
          fi

