name: Run Script

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Search for charts
        id: search-charts
        run: |
          echo "test-chart-name=test-chart-name-long" >> $GITHUB_OUTPUT
        shell: bash
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            print(${{ env.TEST_CHART_NAME}})

