name: Run Script

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      ecr:
        type: string
        required: true
        default: "test-chart-name-long"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Get chart name
        shell: bash
        run: |
          if [[ ${{ inputs.ecr }} == *"cwp"* ]] || [[ ${{ inputs.ecr }} == *"zpc"* ]];
          then
              echo "String contains substring."
              echo "ECR_NAME=${{ inputs.ecr }}" >> $GITHUB_ENV
          else
              echo "String does not contain substring."
              echo "ECR_NAME="zpc-"+${{ inputs.ecr }}" >> $GITHUB_ENV
          fi
      - name: print var
        shell: bash
        run: echo ${{ env.ECR_NAME }}

