name: Run Script

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      ecr:
        type: string
        required: true
        default: "test-chart-name-long"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            print("test-chart-name" + get_input(ecr) )

